In [9]:
import pandas as pd
from susse.estimators.data.wrangling import wrangle_CAMSRAD_data, wrangle_Solcast_data, wrangle_NREL_Data

# CAMSRAD Data Processing

In [10]:
df = wrangle_CAMSRAD_data('Data/irradiation_estimates/CBE_Data/Egypt/raw/CAMSRAD_location1.csv')

In [11]:
df.head()

,TAO (kWh/m2/day),Clear sky GHI (kWh/m2/day),Clear sky BHI (kWh/m2/day),Clear sky DHI (kWh/m2/day),Clear sky DNI (kWh/m2/day),GHI (kWh/m2/day),BHI (kWh/m2/day),DHI (kWh/m2/day),DNI (kWh/m2/day),Reliability,Day
0,9.949236,7.064093,5.063737,2.000355,7.190065,7.064093,5.063737,2.000355,7.190065,0.9865,2023-09-01
1,9.909081,7.397833,6.086805,1.311028,8.844054,7.397833,6.086805,1.311028,8.844054,0.9872,2023-09-02
2,9.868389,7.374729,5.954697,1.420032,8.687866,7.129047,5.438491,1.690557,8.094882,0.9826,2023-09-03
3,9.827185,7.328903,5.809644,1.519259,8.539902,7.328903,5.809644,1.519259,8.539902,0.9833,2023-09-04
4,9.785438,7.287530,5.718695,1.568834,8.398243,7.287530,5.718695,1.568834,8.398243,0.9840,2023-09-05

# NREL Data Processing

In [14]:
df = wrangle_Solcast_data('Data/irradiation_estimates/CBE_Data/Egypt/raw/Solcast_Location1_29.887561_32.460447_fixed_23_180_PT60M.csv')

In [15]:
df.head()

,air_temp (°C),clearsky_dhi (kWh/m2/day),clearsky_dni (kWh/m2/day),clearsky_ghi (kWh/m2/day),clearsky_gti (kWh/m2/day),dhi (kWh/m2/day),dni (kWh/m2/day),ghi (kWh/m2/day),gti (kWh/m2/day)
period_end,,,,,,,,,
2023-09-01 00:00:00+03:00,29.350000,1.965,6.846,6.790,7.079,2.023,6.599,6.743,7.030
2023-09-02 00:00:00+03:00,28.458333,1.625,7.561,6.995,7.338,1.693,7.253,6.944,7.289
2023-09-03 00:00:00+03:00,28.458333,1.696,7.492,7.019,7.384,1.834,7.153,6.925,7.276
2023-09-04 00:00:00+03:00,28.791667,2.006,6.789,6.833,7.193,2.006,6.779,6.831,7.193
2023-09-05 00:00:00+03:00,30.291667,1.556,7.950,7.072,7.492,1.556,7.947,7.071,7.492

# NREL Data Processing