In [1]:
from susse import irradiation
kampala = irradiation.Location(latitude=0.347594, longitude=32.58210, timezone='Africa/Kampala')

In [2]:
kampala.altitude

1202.0

In [3]:
estimator = irradiation.IrradianceEstimator(kampala)

In [4]:
pipeline = irradiation.IrradiancePipeline(estimator)

In [5]:
pipeline.run(
    start_date='2023-01-01',
    end_date='2023-01-03',
    cloud_cover_fraction=0.2,
    surface_tilts=[0],
    surface_azimuth=180
)

In [6]:
print(f"times: {type(pipeline.times)}\n"
      f"clearsky_irradiance: {type(pipeline.clear_sky)}\n"
      f"adjusted_ghi: {type(pipeline.adjusted_ghi)}\n"
      f"solar_position: {type(pipeline.solar_position)}\n"
      f"dhi: {type(pipeline.dhi)}\n"
      f"dni: {type(pipeline.dni)}\n"
      f"poa: {type(pipeline.poa_irradiance)}\n"
)

times: <class 'pandas.core.indexes.datetimes.DatetimeIndex'>
clearsky_irradiance: <class 'pandas.core.frame.DataFrame'>
adjusted_ghi: <class 'numpy.ndarray'>
solar_position: <class 'pandas.core.frame.DataFrame'>
dhi: <class 'numpy.ndarray'>
dni: <class 'numpy.ndarray'>
poa: <class 'dict'>

In [7]:
pipeline.solar_position.head()

,apparent_zenith,zenith,apparent_elevation,elevation,azimuth,equation_of_time
2023-01-01 00:00:00+03:00,153.924968,153.924968,-63.924968,-63.924968,208.557952,-3.128158
2023-01-01 01:00:00+03:00,157.235367,157.235367,-67.235367,-67.235367,175.729947,-3.147915
2023-01-01 02:00:00+03:00,152.049563,152.049563,-62.049563,-62.049563,145.452888,-3.167663
2023-01-01 03:00:00+03:00,141.684446,141.684446,-51.684446,-51.684446,128.576779,-3.187402
2023-01-01 04:00:00+03:00,129.241247,129.241247,-39.241247,-39.241247,120.019771,-3.207132

In [9]:
estimator.decompose_irradiance(
    ghi=pipeline.adjusted_ghi,
    solar_zenith=pipeline.solar_position["zenith"].values,
    times=pipeline.times
    )

                                  dni         dhi        kt
2023-01-01 00:00:00+03:00    0.000000    0.000000  0.000000
2023-01-01 01:00:00+03:00    0.000000    0.000000  0.000000
2023-01-01 02:00:00+03:00    0.000000    0.000000  0.000000
2023-01-01 03:00:00+03:00    0.000000    0.000000  0.000000
2023-01-01 04:00:00+03:00    0.000000    0.000000  0.000000
2023-01-01 05:00:00+03:00    0.000000    0.000000  0.000000
2023-01-01 06:00:00+03:00    0.000000    0.000000  0.000000
2023-01-01 07:00:00+03:00    0.000000    8.602585  0.093599
2023-01-01 08:00:00+03:00  221.426333  123.882409  0.489759
2023-01-01 09:00:00+03:00  379.129685  200.549346  0.562411
2023-01-01 10:00:00+03:00  471.833899  250.214584  0.598607
2023-01-01 11:00:00+03:00  525.885561  282.005467  0.618645
2023-01-01 12:00:00+03:00  553.828972  299.607933  0.628825
2023-01-01 13:00:00+03:00  561.193797  304.408768  0.631495
2023-01-01 14:00:00+03:00  549.331342  296.711087  0.627192
2023-01-01 15:00:00+03:00  516.040828  276.011994  0.615034
2023-01-01 16:00:00+03:00  454.533609  240.546390  0.592059
2023-01-01 17:00:00+03:00  349.836785  185.753211  0.550252
2023-01-01 18:00:00+03:00  171.574976  100.472293  0.461003
2023-01-01 19:00:00+03:00    0.000000    0.000000  0.000000
2023-01-01 20:00:00+03:00    0.000000    0.000000  0.000000
2023-01-01 21:00:00+03:00    0.000000    0.000000  0.000000
2023-01-01 22:00:00+03:00    0.000000    0.000000  0.000000
2023-01-01 23:00:00+03:00    0.000000    0.000000  0.000000
2023-01-02 00:00:00+03:00    0.000000    0.000000  0.000000
2023-01-02 01:00:00+03:00    0.000000    0.000000  0.000000
2023-01-02 02:00:00+03:00    0.000000    0.000000  0.000000
2023-01-02 03:00:00+03:00    0.000000    0.000000  0.000000
2023-01-02 04:00:00+03:00    0.000000    0.000000  0.000000
2023-01-02 05:00:00+03:00    0.000000    0.000000  0.000000
2023-01-02 06:00:00+03:00    0.000000    0.000000  0.000000
2023-01-02 07:00:00+03:00    0.000000    7.824606  0.085133
2023-01-02 08:00:00+03:00  219.985691  123.205326  0.488982
2023-01-02 09:00:00+03:00  378.382752  200.167781  0.562103
2023-01-02 10:00:00+03:00  471.473358  250.010563  0.598468
2023-01-02 11:00:00+03:00  525.764831  281.930595  0.618597
2023-01-02 12:00:00+03:00  553.882692  299.641601  0.628841
2023-01-02 13:00:00+03:00  561.398332  304.541948  0.631565
2023-01-02 14:00:00+03:00  549.691498  296.941073  0.627320
2023-01-02 15:00:00+03:00  516.590271  276.343210  0.615233
2023-01-02 16:00:00+03:00  455.348947  240.997081  0.592366
2023-01-02 17:00:00+03:00  351.075570  186.372334  0.550772
2023-01-02 18:00:00+03:00  173.489162  101.372750  0.462192
2023-01-02 19:00:00+03:00    0.000000    0.000000  0.000000
2023-01-02 20:00:00+03:00    0.000000    0.000000  0.000000
2023-01-02 21:00:00+03:00    0.000000    0.000000  0.000000
2023-01-02 22:00:00+03:00    0.000000    0.000000  0.000000
2023-01-02 23:00:00+03:00    0.000000    0.000000  0.000000
2023-01-03 00:00:00+03:00    0.000000    0.000000  0.000000